-- Monarch Color plastisol stock colors, from the shop's Monarch color chart (PMS reference + hex for each).
-- Grouped by the chart's sections. Bora Bora Sand (seeded in 095) is updated in place.
update public.stock_inks set line='Standard & Athletic', pms='9224 C', hex='#F2E9DB', notes='', sort=138, updated_at=now() where brand='Monarch Color' and name='Bora Bora Sand' and archived_at is null;
insert into public.stock_inks (brand, line, name, product, pms, hex, notes, sort, created_by) values
('Monarch Color','Standard & Athletic','Lemon Yellow','','108 C','#FEDB00','',101,'Monarch chart'),
('Monarch Color','Standard & Athletic','Rich Yellow','','122 C','#FED141','',102,'Monarch chart'),
('Monarch Color','Standard & Athletic','Gold Yellow','','1235 C','#FFB81C','',103,'Monarch chart'),
('Monarch Color','Standard & Athletic','Orange','','1645 C','#FF6A39','',104,'Monarch chart'),
('Monarch Color','Standard & Athletic','Athletic Orange','','3556 C','#E63422','',105,'Monarch chart'),
('Monarch Color','Standard & Athletic','Academy Orange','','167 C','#BE531C','',106,'Monarch chart'),
('Monarch Color','Standard & Athletic','Vivid Red','','186 C','#C8102E','',107,'Monarch chart'),
('Monarch Color','Standard & Athletic','Scarlet Red','','1795 C','#D22630','',108,'Monarch chart'),
('Monarch Color','Standard & Athletic','Bold Red','','180 C','#BE3A34','',109,'Monarch chart'),
('Monarch Color','Standard & Athletic','Cardinal Red','','187 C','#A6192E','',110,'Monarch chart'),
('Monarch Color','Standard & Athletic','Maroon','','207 C','#A50034','',111,'Monarch chart'),
('Monarch Color','Standard & Athletic','Pure Pink','','926 C','#F7D0DC','',112,'Monarch chart'),
('Monarch Color','Standard & Athletic','Lilac','','522 C','#BA9CC5','',113,'Monarch chart'),
('Monarch Color','Standard & Athletic','Violet','','269 C','#51284F','',114,'Monarch chart'),
('Monarch Color','Standard & Athletic','Magenta','','512 C','#93328E','',115,'Monarch chart'),
('Monarch Color','Standard & Athletic','Dark Purple','','2112 C','#322E7E','',116,'Monarch chart'),
('Monarch Color','Standard & Athletic','Ultramarine','','072 C Blue','#10069F','',117,'Monarch chart'),
('Monarch Color','Standard & Athletic','Navy Blue','','7547 C','#16232A','',118,'Monarch chart'),
('Monarch Color','Standard & Athletic','Light Navy Blue','','2380 C','#273248','',119,'Monarch chart'),
('Monarch Color','Standard & Athletic','Royal Blue','','288 C','#002D72','',120,'Monarch chart'),
('Monarch Color','Standard & Athletic','Moon Blue','','2945 C','#004C97','',121,'Monarch chart'),
('Monarch Color','Standard & Athletic','Columbia Blue','','7690 C','#0076A8','',122,'Monarch chart'),
('Monarch Color','Standard & Athletic','Sky Blue','','2141 C','#88BDE8','',123,'Monarch chart'),
('Monarch Color','Standard & Athletic','Ocean Blue','','2393 C','#0090CB','',124,'Monarch chart'),
('Monarch Color','Standard & Athletic','Caribbean Blue','','638 C','#00AFD7','',125,'Monarch chart'),
('Monarch Color','Standard & Athletic','Aqua Blue','','3557 C','#00797C','',126,'Monarch chart'),
('Monarch Color','Standard & Athletic','Jungle Green','','341 C','#007A53','',127,'Monarch chart'),
('Monarch Color','Standard & Athletic','Light Green','','2257 C','#00AD50','',128,'Monarch chart'),
('Monarch Color','Standard & Athletic','Forest Green','','2417 C','#189B6B','',129,'Monarch chart'),
('Monarch Color','Standard & Athletic','Pine Green','','336 C','#00664F','',130,'Monarch chart'),
('Monarch Color','Standard & Athletic','Dark Green','','4210 C','#305043','',131,'Monarch chart'),
('Monarch Color','Standard & Athletic','Dark Brown','','476 C','#4E3629','',132,'Monarch chart'),
('Monarch Color','Standard & Athletic','Light Brown','','7528 C','#C5B9AC','',133,'Monarch chart'),
('Monarch Color','Standard & Athletic','Khaki','','467 C','#D3BC8D','',134,'Monarch chart'),
('Monarch Color','Standard & Athletic','Vegas Gold','','4543 C','#DFCFA3','',135,'Monarch chart'),
('Monarch Color','Standard & Athletic','Dolphin Grey','','Cool Gray 5 C','#B1B3B3','',136,'Monarch chart'),
('Monarch Color','Standard & Athletic','Shark Grey','','Cool Gray 6 C','#A7A8AA','',137,'Monarch chart'),
('Monarch Color','Process','Process Cyan','','','#00AEEF','Chart reference: Process Cyan (no PMS).',139,'Monarch chart'),
('Monarch Color','Process','Process Magenta','','','#EC008C','Chart reference: Process Magenta (no PMS).',140,'Monarch chart'),
('Monarch Color','Process','Process Yellow','','','#FFF200','Chart reference: Process Yellow (no PMS).',141,'Monarch chart'),
('Monarch Color','Process','Volcanic Magenta','','','#FF0B9B','Chart reference: Process Magenta +5% (no PMS).',142,'Monarch chart'),
('Monarch Color','Blending','G/S Yellow','','109 C','#FFD100','',143,'Monarch chart'),
('Monarch Color','Blending','R/S Yellow','','2010 C','#FFAD00','',144,'Monarch chart'),
('Monarch Color','Blending','Orange','','1665 C','#DC4405','',145,'Monarch chart'),
('Monarch Color','Blending','B/S Red','','1955 C','#8A1538','',146,'Monarch chart'),
('Monarch Color','Blending','Y/S Red','','199 C','#D50032','',147,'Monarch chart'),
('Monarch Color','Blending','Green','','3288 C','#008264','',148,'Monarch chart'),
('Monarch Color','Blending','G/S Blue','','2945 C','#004C97','',149,'Monarch chart'),
('Monarch Color','Blending','R/S Blue','','4152 C','#135193','',150,'Monarch chart'),
('Monarch Color','Blending','Ultramarine','','2736 C','#1E22AA','',151,'Monarch chart'),
('Monarch Color','Blending','Violet','','276 C','#221C35','',152,'Monarch chart'),
('Monarch Color','Blending','Cerise','','7649 C','#8A1B61','',153,'Monarch chart'),
('Monarch Color','Blending','Mixing Black','','Black 3 C','#212721','',154,'Monarch chart'),
('Monarch Color','Fluorescent','Neon Yellow','','803 C','#FFE900','',155,'Monarch chart'),
('Monarch Color','Fluorescent','Neon Rich Yellow','','804 C','#FFAA4D','',156,'Monarch chart'),
('Monarch Color','Fluorescent','Neon Orange','','805 C','#FF7276','',157,'Monarch chart'),
('Monarch Color','Fluorescent','Neon Pink','','806 C','#FF3EB5','',158,'Monarch chart'),
('Monarch Color','Fluorescent','Neon Magenta','','','#FF0090','Chart reference: Fluorescent Magenta (no PMS).',159,'Monarch chart'),
('Monarch Color','Fluorescent','Neon Red','','','#FF2D2D','Chart reference: Fluorescent Red (no PMS).',160,'Monarch chart'),
('Monarch Color','Fluorescent','Neon Rocket Red','','','#FF3366','Chart reference: Fluorescent B/S Red (no PMS).',161,'Monarch chart'),
('Monarch Color','Fluorescent','Neon Green','','802 C','#44D62C','',162,'Monarch chart'),
('Monarch Color','Fluorescent','Neon Blue','','801 C','#009ACE','',163,'Monarch chart'),
('Monarch Color','Fluorescent','Neon Purple','','','#B026FF','Chart reference: Fluorescent Purple (no PMS).',164,'Monarch chart'),
('Monarch Color','Specialty','Platinum Metallic Silver','','','#B5BABD','Chart reference: Metallic silver (no PMS). Shown flat on the chart; ask Monarch for a physical chip.',165,'Monarch chart'),
('Monarch Color','Specialty','Gold Sparkle','','','#C6A135','Chart reference: Sparkle gold (no PMS). Shown flat on the chart; ask Monarch for a physical chip.',166,'Monarch chart'),
('Monarch Color','Specialty','Silver Sparkle','','','#C8CDD0','Chart reference: Sparkle silver (no PMS). Shown flat on the chart; ask Monarch for a physical chip.',167,'Monarch chart'),
('Monarch Color','Specialty','Glow in the Dark','','','#DCE9D6','Chart reference: Glow (no PMS). Shown flat on the chart; ask Monarch for a physical chip.',168,'Monarch chart');
